### ISSUE TITLE
don't support for ue5.4.2

### ISSUE THREAD

**Issue by smallPotatoBoy** [Vital-Volkov/Stereoscopic-3D-system-for-Unreal-Engine-5#3]
![屏幕截图 2024-06-21 195133](https://github.com/Vital-Volkov/Stereoscopic-3D-system-for-Unreal-Engine-5/assets/50900145/617b6eed-20bc-4c13-9bca-276727e992a6)

some material function has changed in ue5.4.2, we can't see 3d anymore in vertical mode ...
any help please ,thank you!

**Comment by Vital-Volkov** [comment]
Looks like the A/B order of "MaterialX SplitTB" function was changed so the fastest way to fix it for UE5.4 is just swap A/B lines but it will stop showing correct in UE5.
I fixed this for working correct in all versions of UE5 by just changing Render Texture properties from Clamp to Wrap(Repeat) so no need to shift UV coordinates for right texture to -1 and as result of different order of A/B lines of "MaterialX SplitTB" function Over is left eye and Under is right eye for UE5 and vise versa for UE5.4 so just use "Swap Left-Right View" if required.

**Comment by smallPotatoBoy** [comment]
yes,but the viewport is showing  2 lines by 2 lines now(see image ), is not correct,we can't see 3D like this way,
how can i showing this 1 line by 1 line in vertical mode?

![image](https://github.com/Vital-Volkov/Stereoscopic-3D-system-for-Unreal-Engine-5/assets/50900145/5f06ba43-7c3f-49e0-860c-5ad7863a93c8)

![20240624-145008](https://github.com/Vital-Volkov/Stereoscopic-3D-system-for-Unreal-Engine-5/assets/50900145/3641082b-933e-4d71-b518-d10818d86629)

thanks a lot for your help!

**Comment by smallPotatoBoy** [comment]
is very helpful,thanks a lot for your support!

**Comment by Vital-Volkov** [comment]
Ok looking at your screenshots I understand what you mean. Above I solved another problem with the Over/Under method :)) because I checked the Interlace Vertical method and it works fine in my case. This line desynchronisation with screen lines happens when you are not using the native resolution of your screen. For example if screen resolution is 1920 but game resolution in fullscreen mode is 1280(any different from 1920) then this problem happens. But if game resolution matches screen resolution but problem still exists this means UE somehow set not the correct resolution for Render Texture. Need to test this.

Does it work correctly for you with the same conditions hardware/software settings with the older UE version?

**Comment by smallPotatoBoy** [comment]
Of course,it work correctly for me with the same conditions hardware/software settings with the older UE version,and your analysis is very correct,if game resolution matches screen resolution but problem still exists this means UE somehow set not the correct resolution for Render Texture.
Based on this， we solved this problem！

 I couldn’t have completed the task without your help！:)

As you can see ,this is my screenshots in last day：

![屏幕截图 2024-06-24 152345](https://github.com/Vital-Volkov/Stereoscopic-3D-system-for-Unreal-Engine-5/assets/50900145/bb8def0d-4ba7-4b20-9b03-e061efc65f66)

![屏幕截图 2024-06-24 151744](https://github.com/Vital-Volkov/Stereoscopic-3D-system-for-Unreal-Engine-5/assets/50900145/a80074b8-3d10-4297-bf13-607649bfe7f9)
